seml:
  name: products_localprbcd
  executable: experiments/experiment_local_attack_direct.py
  project_root_dir: ../..
  output_dir: config/attack_evasion_local_direct/output

slurm:
  experiments_per_job: 1
  sbatch_options:
    gres: gpu:1       # num GPUs
    mem: 24G          # memory
    cpus-per-task: 4  # num cores
    time: 0-08:00     # max time, D-HH:MM

fixed:
  data_dir: data/
  dataset: ogbn-products
  binary_attr: False
  nodes_topk: 40
  nodes: None
  artifact_dir: cache
  model_storage_type: pretrained
  device: 0
  data_device: cpu
  debug_level: info
  attack_params.epochs: 40
  attack_params.fine_tune_epochs: 10
  attack_params.display_step: 1
  attack_params.do_synchronize: True
  attack_params.ppr_recalc_at_end: True
  attack_params.ppr_cache_params:
    data_artifact_dir: cache
    data_storage_type: ppr

grid:
  seed:
    type: choice
    options:
      - 0
      - 1
      - 5
  make_undirected:
    type: choice
    options:
      - False
  epsilons:
    type: choice
    options:
      - [0.05]
      - [0.1]
      - [0.25]
      - [0.5]
      - [1.0]

localprbcd_pprgo:
  fixed:
    attack: LocalBatchedPRBCD
    model_label: Vanilla PPRGo
    attack_params.loss_type: Margin
    attack_params.block_size: 20_000
    attack_params.lr_factor: 1e-1


localprbcd_pprgo_median:
  fixed:
    attack: LocalBatchedPRBCD
    model_label: Soft Median PPRGo (T=1.0)
    attack_params.loss_type: Margin
    attack_params.block_size: 20_000
    attack_params.lr_factor: 1e-1

