seml:
  name: gnn_cora_citeseer
  executable: experiments/experiment_train.py
  project_root_dir: ../..
  output_dir: config/train/output

slurm:
  experiments_per_job: 1
  sbatch_options:
    gres: gpu:1       # num GPUs
    mem: 16G          # memory
    cpus-per-task: 4  # num cores
    time: 0-01:00     # max time, D-HH:MM

fixed:
  train_params:
    lr: 1e-2
    weight_decay: 1e-3
    patience: 300
    max_epochs: 3000
  artifact_dir: cache
  model_storage_type: pretrained
  device: 0
  data_device: 0
  make_undirected: True
  binary_attr: False

grid:
  dataset:
    type: choice
    options:
      - cora_ml
      - citeseer

  seed:
    type: choice
    options:
      - 0
      - 1
      - 5

gcn:
  fixed:
    model_params:
      label: Vanilla GCN
      model: GCN
      do_cache_adj_prep: True
      n_filters: 64
      dropout: 0.5
      svd_params: None
      jaccard_params: None
      gdc_params: None

dense_gcn:
  fixed:
    model_params:
      label: Vanilla Dense GCN
      model: DenseGCN
      do_cache_adj_prep: True
      n_filters: 64
      dropout: 0.5
      svd_params: None
      jaccard_params: None
      gdc_params: None

gdc:
  fixed:
    model_params:
      label: Vanilla GDC
      model: GCN
      do_cache_adj_prep: True
      n_filters: 64
      dropout: 0.5
      svd_params: None
      jaccard_params: None
      gdc_params:
          alpha: 0.15
          k: 64

soft_medoid_gdc_t0_5:
  fixed:
    model_params:
      label: Soft Medoid GDC (T=0.5)
      model: RGNN
      dropout: 0.5
      n_filters: 64
      mean: soft_k_medoid
      mean_kwargs:
          k: 64
          temperature: 0.5
          with_weight_correction: True
      gdc_params:
          alpha: 0.15
          k: 64
      svd_params: None
      jaccard_params: None
      do_cache_adj_prep: True

svd_rank50:
  fixed:
    model_params:
      label: SVD GCN (rank=50)
      model: GCN
      do_cache_adj_prep: True
      n_filters: 64
      dropout: 0.5
      svd_params: 
        rank: 50
      jaccard_params: None
      gdc_params: None

svd_rank100:
  fixed:
    model_params:
      label: SVD GCN (rank=100)
      model: GCN
      do_cache_adj_prep: True
      n_filters: 64
      dropout: 0.5
      svd_params: 
        rank: 100
      jaccard_params: None
      gdc_params: None

jaccard:
  fixed:
    model_params:
      label: Jaccard GCN
      model: GCN
      do_cache_adj_prep: True
      n_filters: 64
      dropout: 0.5
      svd_params: None
      jaccard_params: 
        threshold: 0.01
      gdc_params: None

rgcn:
  fixed:
    model_params:
      label: RGCN
      model: RGCN
      do_cache_adj_prep: True
      n_filters: 64
      svd_params: None
      jaccard_params: None
      gdc_params: None