seml:
  name: rgnn_at_scale_train
  executable: experiments/experiment_train.py
  project_root_dir: ../..
  output_dir: config/train/output

slurm:
  experiments_per_job: 1
  sbatch_options:
    gres: gpu:1       # num GPUs
    mem: 16G          # memory
    cpus-per-task: 4  # num cores
    time: 0-02:00     # max time, D-HH:MM

fixed:
  train_params:
    lr: 1e-2
    weight_decay: 1e-3
    patience: 300
    max_epochs: 3000
  artifact_dir: cache
  model_storage_type: pretrained
  device: 0
  data_device: 0
  make_undirected: True
  binary_attr: False

  dataset: pubmed

grid: 
  seed:
    type: choice
    options:
      - 0
      - 1
      - 5

gcn:
  fixed:
    model_params:
      label: Vanilla GCN
      model: GCN
      dropout: 0.5
      n_filters: 64
      gdc_params: None
      svd_params: None
      jaccard_params: None
      do_cache_adj_prep: True

gdc:
  fixed:
    model_params:
      label: Vanilla GDC
      model: GCN
      dropout: 0.5
      n_filters: 64
      gdc_params:
          alpha: 0.15
          k: 32
          use_cpu: True
      svd_params: None
      jaccard_params: None
      do_cache_adj_prep: True

soft_medoid_gdc_t1_0:
  fixed:
    model_params:
      label: Soft Medoid GDC (T=1.0)
      model: RGNN
      dropout: 0.5
      n_filters: 64
      mean: soft_k_medoid
      mean_kwargs:
          k: 64
          temperature: 1.0
          with_weight_correction: True
      gdc_params:
          alpha: 0.15
          k: 64
          use_cpu: True
      svd_params: None
      jaccard_params: None
      do_cache_adj_prep: True

soft_medoid_gdc_t0_5:
  fixed:
    model_params:
      label: Soft Medoid GDC (T=0.5)
      model: RGNN
      dropout: 0.5
      n_filters: 64
      mean: soft_k_medoid
      mean_kwargs:
          k: 64
          temperature: 0.5
          with_weight_correction: True
      gdc_params:
          alpha: 0.15
          k: 64
          use_cpu: True
      svd_params: None
      jaccard_params: None
      do_cache_adj_prep: True

soft_medoid_gdc_t0_2:
  fixed:
    model_params:
      label: Soft Medoid GDC (T=0.2)
      model: RGNN
      dropout: 0.5
      n_filters: 64
      mean: soft_k_medoid
      mean_kwargs:
          k: 64
          temperature: 0.2
          with_weight_correction: True
      gdc_params:
          alpha: 0.15
          k: 64
          use_cpu: True
      svd_params: None
      jaccard_params: None
      do_cache_adj_prep: True

soft_median_gdc_t1_0:
  fixed:
    model_params:
      label: Soft Median GDC (T=1.0)
      model: RGNN
      dropout: 0.5
      n_filters: 64
      mean: soft_median
      mean_kwargs:
          temperature: 1.0
      gdc_params:
          alpha: 0.15
          k: 64
          use_cpu: True
      svd_params: None
      jaccard_params: None
      do_cache_adj_prep: True

soft_median_gdc_t0_5:
  fixed:
    model_params:
      label: Soft Median GDC (T=0.5)
      model: RGNN
      dropout: 0.5
      n_filters: 64
      mean: soft_median
      mean_kwargs:
          temperature: 0.5
      gdc_params:
          alpha: 0.15
          k: 64
          use_cpu: True
      svd_params: None
      jaccard_params: None
      do_cache_adj_prep: True

soft_median_gdc_t0_2:
  fixed:
    model_params:
      label: Soft Median GDC (T=0.2)
      model: RGNN
      dropout: 0.5
      n_filters: 64
      mean: soft_median
      mean_kwargs:
          temperature: 0.2
      gdc_params:
          alpha: 0.15
          k: 64
          use_cpu: True
      svd_params: None
      jaccard_params: None
      do_cache_adj_prep: True

pprgo:
  fixed:
    data_device: 'cpu'
    model_params:
      label: Vanilla PPRGo
      model: PPRGo
      ppr_normalization: 'row' 
      batch_norm: False
      topk: 256
      n_filters: 256
      n_layers: 2
      alpha: 0.1
      eps: 1e-6
      dropout: 0.25
    train_params:
      lr: 1e-4
      weight_decay:  1e-3
      batch_mult_val: 1
      batch_size: 10240
      forward_batch_size: 8192

soft_median_rpprgo_t1_0:
  fixed:
    data_device: 'cpu'
    model_params:
      label: Soft Median PPRGo (T=1.0)
      model: RobustPPRGo
      ppr_normalization: 'row' 
      batch_norm: False
      topk: 256
      n_filters: 256
      alpha: 0.1
      eps: 1e-6
      dropout: 0.25
      n_layers: 2
      mean: soft_median
      mean_kwargs: 
        temperature: 1.0
    train_params:
      lr: 1e-4
      weight_decay:  1e-3
      batch_mult_val: 1
      batch_size: 8192
      forward_batch_size: 8192

soft_median_rpprgo_t5_0:
  fixed:
    data_device: 'cpu'
    model_params:
      label: Soft Median PPRGo (T=5.0)
      model: RobustPPRGo
      ppr_normalization: 'row' 
      batch_norm: False
      topk: 256
      n_filters: 256
      alpha: 0.1
      eps: 1e-6
      dropout: 0.25
      n_layers: 2
      mean: soft_median
      mean_kwargs: 
        temperature: 5.0
    train_params:
      lr: 1e-4
      weight_decay:  1e-3
      batch_mult_val: 1
      batch_size: 8192
      forward_batch_size: 8192
