seml:
  name: rgnn_at_scale_attack_evasion_global_transfer
  executable: experiments/experiment_global_attack_transfer.py
  project_root_dir: ../..
  output_dir: config/attack_evasion_global_transfer/output

slurm:
  experiments_per_job: 1
  sbatch_options:
    gres: gpu:1       # num GPUs
    mem: 16G          # memory
    cpus-per-task: 4  # num cores
    time: 0-08:00     # max time, D-HH:MM

fixed:
  data_dir: data/
  epsilons: [0, 0.01, 0.05, 0.1]
  artifact_dir: cache
  pert_adj_storage_type: evasion_global_transfer_adj
  pert_attr_storage_type: evasion_global_transfer_attr
  model_storage_type: pretrained
  surrogate_model_storage_type: pretrained
  device: 0
  data_device: 0 
  make_undirected: True
  dataset: pubmed

grid:
  seed:
    type: choice
    options:
      - 0
      - 1
      - 5
  model_label:
    type: choice
    options:
      - Vanilla GCN
      - Vanilla GDC
      - Soft Medoid GDC (T=1.0)
      - Soft Medoid GDC (T=0.5)
      - Soft Medoid GDC (T=0.2)
      - Soft Median GDC (T=1.0)
      - Soft Median GDC (T=0.5)
      - Soft Median GDC (T=0.2)
      - Vanilla PPRGo
      - Soft Median PPRGo (T=1.0)
      - Soft Median PPRGo (T=5.0)

greedy_rbcd:
  fixed:
    attack: GreedyRBCD
    binary_attr: False
    surrogate_model_label: Vanilla GCN
    attack_params:
      block_size: 2_500_000
      loss_type: MCE

prbcd:
  fixed:
    attack: PRBCD
    binary_attr: False
    surrogate_model_label: Vanilla GCN
    attack_params:
      keep_heuristic: WeightOnly
      block_size: 2_500_000
      do_synchronize: True
  grid: 
    attack_params:
      type: parameter_collection
      params:
        loss_type: 
          type: choice
          options:
            - tanhMargin

dice:
  fixed:
    attack: DICE
    binary_attr: False
    surrogate_model_label: Vanilla GCN