seml:
  name: rgnn_at_scale_attack_evasion_global_direct
  executable: experiments/experiment_global_attack_direct.py
  project_root_dir: ../..
  output_dir: config/attack_evasion_global_direct/output

slurm:
  experiments_per_job: 1
  sbatch_options:
    gres: gpu:1       # num GPUs
    mem: 4G          # memory
    cpus-per-task: 4  # num cores
    time: 0-08:00     # max time, D-HH:MM

fixed:
  data_dir: data/
  artifact_dir: cache
  pert_adj_storage_type: evasion_global_adj
  pert_attr_storage_type: evasion_global_attr
  model_storage_type: pretrained
  device: 0
  data_device: 0
  make_undirected: True

grid:
  dataset:
    type: choice
    options:
      - cora_ml
      - citeseer

  seed:
    type: choice
    options:
      - 0
      - 1
      - 5
  epsilons: 
    type: choice
    options:
      - [0, 0.01, 0.05, 0.10, 0.25, 0.5, 1.0]

  model_label:
    type: choice
    options:
     - Vanilla GCN
     - Vanilla GDC
     - Soft Median GDC (T=1.0)
     - Soft Median GDC (T=0.5)
     - Soft Median GDC (T=0.2)

greedy_rbcd:
  fixed:
    attack: GreedyRBCD
    attack_params:
      block_size: 100_000
      loss_type: MCE

prbcd:
  fixed:
    binary_attr: False
    attack: PRBCD
    attack_params:
      epochs: 500
      fine_tune_epochs: 100
      keep_heuristic: WeightOnly
      block_size: 100_000
      do_synchronize: True
      loss_type: tanhMargin
